server:
  port: 9999

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9001/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"