spring:
  data:
    mongodb:
      database: bhu
  kafka:
    bootstrap-servers: localhost:9096
  main:
    web-application-type: none

poc:
  kafka:
    enabled: false

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG